name: Setup piqtree
description: "Setup Python and Fetch Static Library."
inputs:
  python-version:
    description: "Python version."
    required: true
  cache-key:
    description: "Key for static library cache."
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache IQ-TREE (Windows)
      if: runner.os == 'Windows'
      uses: actions/cache/restore@v4
      id: cache-windows
      with:
        key: ${{ inputs.cache-key }}
        path: |
          src/piqtree/_libiqtree/iqtree.lib
          src/piqtree/_libiqtree/iqtree.dll
        fail-on-cache-miss: true

    - name: Cache IQ-TREE (Linux/macOS)
      if: runner.os != 'Windows'
      uses: actions/cache/restore@v4
      id: cache-unix
      with:
        key: ${{ inputs.cache-key }}
        path: |
          src/piqtree/_libiqtree/libiqtree.a
        fail-on-cache-miss: true
