name: Fetch or Build IQ-TREE 2 Static Library
description: "Checks if the IQ-TREE 2 static library exists, if not then building it."
inputs:
  os:
    description: "Runner OS Name."
    required: true
outputs:
  iqtree2-sha:
    description: "SHA for commit of IQ-TREE 2 static library."
    value: ${{ steps.iqtree2-sha.outputs.iqtree2-sha }}
runs:
  using: "composite"
  steps:
    - id: iqtree2-sha
      name: Get IQ-TREE 2 SHA
      shell: bash
      run: |
        cd iqtree2
        IQ_TREE_2_SHA=$(git rev-parse HEAD)
        echo "iqtree2-sha=${IQ_TREE_2_SHA}" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@v4
      id: cache
      with:
        key: libiqtree-${{ inputs.os }}-${{ steps.iqtree2-sha.outputs.iqtree2-sha }}
        path: |
          ${{ inputs.os == 'windows-latest' && 'src/piqtree/_libiqtree/iqtree2.lib\nsrc/piqtree/_libiqtree/iqtree2.dll' || 'src/piqtree/_libiqtree/libiqtree2.a' }}
        lookup-only: true

    - name: Install Boost
      if: runner.os == 'Windows' && steps.cache.outputs.cache-hit != 'true'
      uses: MarkusJx/install-boost@v2.4.5
      id: install-boost
      with:
        boost_version: 1.84.0
        platform_version: 2022
        toolset: mingw

    - name: Set Boost Environment Variables
      if: runner.os == 'Windows' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Boost_INCLUDE_DIR=${{ steps.install-boost.outputs.BOOST_ROOT }}/include" >> "$GITHUB_ENV"
        echo "Boost_LIBRARY_DIRS=${{ steps.install-boost.outputs.BOOST_ROOT }}/lib" >> "$GITHUB_ENV"

    - name: Debug MSVC Installation
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all
        
    - name: Set Up MSVC for lib.exe
      if: runner.os == 'Windows' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        # Check default VS installation paths
        VSWHERE_PATH="/c/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"

        if [[ -f "$VSWHERE_PATH" ]]; then
            echo "Finding latest MSVC installation..."
            
            MSVC_PATH=$("$VSWHERE_PATH" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath)
            
            if [[ -d "$MSVC_PATH" ]]; then
                MSVC_BIN_PATH="$MSVC_PATH/VC/Tools/MSVC"
                MSVC_VERSION=$(ls "$MSVC_BIN_PATH" | sort -V | tail -n 1)
                LIB_PATH="$MSVC_BIN_PATH/$MSVC_VERSION/bin/Hostx64/x64"

                echo "MSVC found at: $LIB_PATH"
                echo "PATH=$LIB_PATH:$PATH" >> "$GITHUB_ENV"
            else
                echo "MSVC installation not found."
                exit 1
            fi
        else
            echo "vswhere.exe not found, unable to locate MSVC."
            exit 1
        fi

    - name: Verify lib.exe
      if: runner.os == 'Windows' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        which lib.exe || echo "lib.exe not found"

    - name: Build IQ-TREE
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        if [[ "${{ inputs.os }}" == "ubuntu-latest" ]]; then
          sudo ./build_tools/before_all_linux.sh
        elif [[ "${{ inputs.os }}" == "macOS-latest" ]]; then
          ./build_tools/before_all_mac.sh
        elif [[ "${{ inputs.os }}" == "windows-latest" ]]; then
          ./build_tools/before_all_windows.sh
        else
          echo "Unrecognized OS: '${{ inputs.os }}'."
          exit 1
        fi